# Generated by Django 5.1.12 on 2025-11-18 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad_estimada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal_vacunas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appexamen.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='centro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appexamen.centro'),
        ),
        migrations.AddField(
            model_name='centro',
            name='refugio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appexamen.refugio'),
        ),
        migrations.CreateModel(
            name='Revision_veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_salud', models.IntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appexamen.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('animales', models.ManyToManyField(through='appexamen.Animal_vacunas', to='appexamen.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal_vacunas',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appexamen.vacuna'),
        ),
    ]
