# Generated by Django 5.1.12 on 2025-11-18 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexamen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='centro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='appexamen.centro'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='refugio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centro', to='appexamen.refugio'),
        ),
    ]
